### ISSUE TITLE
More detail of multi modal shape completion

### ISSUE THREAD

**Issue by Dtudy** [yccyenchicheng/AutoSDF#10]
Hello Authors,

Did you sample the points on the completed mesh when you evaluate? If yes, how many points are sampled for evaluation? Thank you!

**Comment by yccyenchicheng** [comment]
Yes we sample the points on the completed mesh. 

And we follow [MSC](https://github.com/ChrisWu1997/Multimodal-Shape-Completion) to sample 2048 points.
