### ISSUE TITLE
Could you share the supplementary materials

### ISSUE THREAD

**Issue by HanzhiC** [yccyenchicheng/AutoSDF#15]

**Comment by HanzhiC** [comment]
Thanks for the cool work! Could you share the supp. mat. of your work? Fail to find one through website or arxiv :(

**Comment by yccyenchicheng** [comment]
Sure! Here is the link for the [supp. mat](https://drive.google.com/file/d/1OYibx6SNFIXvSkg2NoS1v-_1orlWavoV/view?usp=sharing). We will find some time to update the website and the arxiv!

Sorry for the inconvenience.
