### ISSUE TITLE
environment problem

### ISSUE THREAD

**Issue by Dhaizei** [yccyenchicheng/AutoSDF#16]
when  installing  ”conda env create -f autosdf.yaml“ ，it has some problems. such as "Could not find a version that satisfies the requirement marching_cubes from versions:none". so how i solve it？

**Comment by yccyenchicheng** [comment]
Hi @Dhaizei, can you try to remove this line: https://github.com/yccyenchicheng/AutoSDF/blob/master/autosdf.yaml#L249

And install the marching_cubes via:
```
pip install PyMCubes
```

Thanks! Please let us know if there are other issues.
