### ISSUE TITLE
Preprocessing files missing

### ISSUE THREAD

**Issue by theNded** [yccyenchicheng/AutoSDF#17]
Hi, thanks for open sourcing the work.

When running the demo, several files are missing in computing the distance field. 
https://github.com/yccyenchicheng/AutoSDF/blob/master/preprocess/process_one_mesh.py#L329

Are there any recommended workarounds to using python scripts for processing a mesh? Or, would you please share the binaries and libraries somewhere? Thank you!

**Comment by yccyenchicheng** [comment]
Hi @theNded,

You can find the binary here: https://github.com/Xharlie/DISN/tree/master/isosurface

You might need to install other dependencies in your system to get this binary works. You can refer to the original repo or ask us here!
