### ISSUE TITLE
Unconditional generation

### ISSUE THREAD

**Issue by XinYu-Andy** [yccyenchicheng/AutoSDF#18]
Hi,
Thanks for your great work!
I find that this work seems to not demonstrate its ability about unconditional generation. Have you tried about this?

**Comment by yccyenchicheng** [comment]
Hi @XinYu-Andy,

Actually, it can! You can start from a completely empty sequence and let the transformer do the job (predict the missing tokens autoregressively).  We also showcase them here on our project page (at the bottom of the webpage): https://yccyenchicheng.github.io/AutoSDF/
