### ISSUE TITLE
Evaluation Scripts

### ISSUE THREAD

**Issue by JiangWenPL** [yccyenchicheng/AutoSDF#2]
Hi Authors, 

Thank you for your excellent work! The demo is pretty impressive but I didn't find the evaluation scripts for shape completion and reconstruction. Could you please provide them or point out where I can find them? Thank you.

**Comment by yccyenchicheng** [comment]
Hi JiangWen,

For the shape completion, we use the script provided from https://github.com/ChrisWu1997/Multimodal-Shape-Completion/tree/master/evaluation.

For the reconstruction,
- IoU: We compute IoU by thresholding SDF at 0. SDF > 0 is considered as free space while <0 is the occupied space. Comparing GT SDF and pred SDF gives us the IoU.
- F1-Score: We use the official implementation from what3d: https://github.com/lmb-freiburg/what3d/blob/master/eval.py
- CD: We use the CD from this repo (which is just a repackaging of the implementation of PyTorch3D): https://github.com/krrish94/chamferdist

Best regard,
Yen-Chi

**Comment by JiangWenPL** [comment]
Thanks a lot!
