### ISSUE TITLE
What preprocessing script?

### ISSUE THREAD

**Issue by JTT94** [yccyenchicheng/AutoSDF#20]
Hello,

Thank you for open sourcing this code. However I am having some trouble with the data preprocessing.

Your scripts assume resolution 64 on a regular/ uniformly spaced grid, however the DISN data from https://github.com/Xharlie/DISN is shape 32**3, not in a regular grid.

In a previously closed issue you said to run a prepocessing script from DISN. Which one and I assume change resolution to 64 somewhere? Do you mean the ("./isosurface/computeDistanceField"? directly on shapnet? Or is there a way to use the previously computed sdf?

**Comment by yccyenchicheng** [comment]
Hi,

Yes, running their code should work: https://github.com/Xharlie/DISN/blob/master/preprocessing/create_point_sdf_fullgrid.py#L338-L342.
