### ISSUE TITLE
ImportError: cannot import name 'dataroot' from 'configs.paths' (/root/yx/AutoSDF/configs/paths.py)

### ISSUE THREAD

**Issue by yangyouzi** [yccyenchicheng/AutoSDF#23]
Thank you for your excellent work, but I am executing the demo_ shape_ The comp.ipynb file encountered some problems, saying that it was unable to import "dataroot" from "configs  path. py". How can I solve this problem?
![image](https://user-images.githubusercontent.com/117643890/209660557-4045b272-9cf0-4d89-b521-f19f8fe5e962.png)
![image](https://user-images.githubusercontent.com/117643890/209660233-8516748c-c07a-489e-a1fa-18842c577f1e.png)
![image](https://user-images.githubusercontent.com/117643890/209660256-e45b7732-2d33-421e-9003-4c1ad18ccc54.png)

**Comment by lx709** [comment]
@yangyouzi , you can change it according to your own data path and log dir.
