### ISSUE TITLE
ask for 'utils.lpips_util'

### ISSUE THREAD

**Issue by GGuo555** [yccyenchicheng/AutoSDF#33]
Hi, thank you for your excellent work! When trying to run the demo_shape_comp.ipynb, I get the error 
'from utils.lpips_util import get_ckpt_path

ModuleNotFoundError: No module named 'utils.lpips_util' '

and I found under /models/networks, there is no folder named 'utils' or any file named 'lpips_util.py', could you please tell me how to get these files or any other options to run the ipynb successfully?

Thanks a lot!

**Comment by lzh07** [comment]
I have the same problem. Have you solved it？

**Comment by GGuo555** [comment]
> I have the same problem. Have you solved it？

I found it not a must-have package for running (it seems that the script is just for evaluation) so I just comment that import line.

**Comment by MingtaoFu** [comment]
It's here.
https://github.com/CompVis/taming-transformers/blob/master/taming/util.py
