### ISSUE TITLE
Baseline models

### ISSUE THREAD

**Issue by thusiyuan** [yccyenchicheng/AutoSDF#4]
Thank you for the great work!

Do you plan to release the baseline models described in the paper like Image-JE?

**Comment by yccyenchicheng** [comment]
Hi Siyuan,

Unfortunately, we do not plan to release the baseline models currently. However, we will update the arxiv paper with the supplementary materials in which we will describe the implementation details of the baselines models.

Thank you!

**Comment by thusiyuan** [comment]
Got it, thanks!

**Comment by yccyenchicheng** [comment]
Hi Siyuan,

Actually, we decided to release them in the near future along with the supplementary materials.

Sorry for the inconvenience and stay tuned!
