### ISSUE TITLE
Minor issue regarding environment and marchingcubes

### ISSUE THREAD

**Issue by VasLem** [yccyenchicheng/AutoSDF#5]
Hi, first off, congratulations for this great work, I am looking forward to train AutoSDF on my biomedical dataset and hopefully help patients with 3d printed scaffolds of 3d completed bones.
There is a minor issue I noticed during the installation. The marchingcubes listed in the anaconda yaml cannot be installed from there, instead it needs to be separately installed, from PyMarchingCubes repo. Also this repo has not been maintained for a while, meaning that the library it depends on, eigen, needs to get a version 3.2 for it to work. Maybe you could incorporate this information in the installation instructions. Other than that, I had no issue running the first step of the code (although I had to make some changes to use cpu, for testing reasons, there are some hard coded pieces of code that do not allow training with gpu-ids=-1)

**Comment by yccyenchicheng** [comment]
Hi @VasLem,

I also found this issue recently and haven't found a way to resolve this yet.

Currently, the workaround I find is installing `mcubes` from https://github.com/pmneila/PyMCubes:
`pip install PyMCubes` and replace all the `import marching_cubes as mcubes` with `import mcubes`.

`mcubes` is only used for visualization so it will affect the training performance.

Thank you for pointing this out and I will add them to the README.md!

As for cpu, the training takes quite a while even on GPU (~7 days for VQ-VAE and ~2 days for the transformers on a single GPU), so we do not handle the cases for running AutoSDF on cpu.
