### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by hanfeng-wu** [yccyenchicheng/AutoSDF#7]
Hello Authors,

Thank you for your great work. I've been running your demos and found out in the ./preprocess/process_one_mesh.py line 329 sdfcommand = './preprocess/isosurface/computeDistanceField' that I do not see the command 'computeDistanceField' in the respective dir, do you have any idea why?

Best,

Hanfeng

**Comment by yccyenchicheng** [comment]
Hi,

`computedDistanceField` can be downloaded from the original DISN repo here: https://github.com/Xharlie/DISN/tree/master/isosurface

Thank you for pointing this out! I will add this to the FAQ.
